name: Build-and-Push-Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag from commit message
        id: extract_tag
        run: |
          MSG="${{ github.event.head_commit.message }}"
          TAG=$(echo "$MSG" | grep -oE 'ver:[0-9]+\.[0-9]+\.[0-9]+' | head -1)
          if [ -z "$TAG" ]; then
            echo "No tag found. Using 'latest'"
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "Using tag: ${TAG#ver:}"
            echo "TAG=${TAG#ver:}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image with version tag
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-nginx:${{ env.TAG }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-nginx:${{ env.TAG }}

      - name: Also tag as latest and push (optional)
        if: env.TAG != 'latest'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-nginx:${{ env.TAG }} ${{ secrets.DOCKER_USERNAME }}/my-nginx:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-nginx:latest

      - name: Done
        run: echo "Docker image ${{ env.TAG }} (and latest) pushed to Docker Hub!"
